resources:
  containers:
  - container: vue_container
    image: vuejs/ci

jobs:
- job: Install
  container: vue_container
  steps:
  - script: |
      npm install
    displayName: 'npm install'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: drop
      targetPath: $(System.DefaultWorkingDirectory)/node_modules
      
- job: Lint
  dependsOn: Install
  container: vue_container
  steps:
  - script: |
      ls
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: drop
      targetPath: $(System.DefaultWorkingDirectory)
  - script: |
      ls
      
    
