resources:
  containers:
  - container: vue_container
    image: vuejs/ci

jobs:
- job: Install
  container: vue_container
  steps:
  - script: |
      npm install
    displayName: 'npm install'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: drop
      targetPath: $(System.DefaultWorkingDirectory)
      
- job: Lint
  dependsOn: Install
  container: vue_container
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: drop
      targetPath: $(System.DefaultWorkingDirectory)
  - script: |
      npm run lint
      npm run flow
      npm run test:types
      
- job: Test e2e
  dependsOn: Install
  container: vue_container
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: drop
      targetPath: $(System.DefaultWorkingDirectory)
  - script: |
      npm run test:e2e -- --env phantomjs
      
- job: ssr-weex
  dependsOn: Install
  container: vue_container
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: drop
      targetPath: $(System.DefaultWorkingDirectory)
  - script: |
      npm run test:ssr
      npm run test:weex
      
    
